-- 적재 스키마는 느슨하게 두고, 안정된 질의 패턴만 뷰로 굳힌다.
-- 뷰는 언제든 DROP/재정의 가능하고 재적재가 필요 없다.
--
-- html_url 계열은 적재 때 지운다(full_name 에서 복원되므로). 복원은 여기서 한다.

CREATE VIEW IF NOT EXISTS starred AS
SELECT
  s.repo_id,
  s.full_name,
  'https://github.com/' || s.full_name              AS url,
  datetime(s.starred_at, 'unixepoch')               AS starred_at,
  json_extract(s.data, '$.owner.login')             AS owner,
  json_extract(s.data, '$.description')             AS description,
  json_extract(s.data, '$.language')                AS language,
  json_extract(s.data, '$.stargazers_count')        AS stars,
  json_extract(s.data, '$.forks_count')             AS forks,
  json_extract(s.data, '$.open_issues_count')       AS open_issues,
  json_extract(s.data, '$.license.spdx_id')         AS license,
  json_extract(s.data, '$.homepage')                AS homepage,
  json_extract(s.data, '$.archived')                AS archived,
  json_extract(s.data, '$.fork')                    AS is_fork,
  json_extract(s.data, '$.size')                    AS size_kb,
  date(json_extract(s.data, '$.created_at'))        AS repo_created,
  date(json_extract(s.data, '$.pushed_at'))         AS last_push,
  s.first_sync,
  s.last_sync
FROM star s
WHERE s.unstarred_sync IS NULL;

-- 뺀 별표. row 는 지우지 않으므로 언제 무엇이 사라졌는지 남는다.
CREATE VIEW IF NOT EXISTS unstarred AS
SELECT
  s.repo_id,
  s.full_name,
  datetime(s.starred_at, 'unixepoch')      AS starred_at,
  datetime(y.finished_at, 'unixepoch')     AS noticed_at,
  json_extract(s.data, '$.language')       AS language,
  json_extract(s.data, '$.description')    AS description
FROM star s
JOIN sync y ON y.id = s.unstarred_sync
WHERE s.unstarred_sync IS NOT NULL;

-- topics 는 배열이라 별도 뷰로 편다. GROUP BY 로 태그 분포를 바로 낼 수 있다.
CREATE VIEW IF NOT EXISTS topic AS
SELECT
  s.repo_id,
  s.full_name,
  j.value AS topic
FROM star s, json_each(s.data, '$.topics') j
WHERE s.unstarred_sync IS NULL;

-- >>> generated by make-views.ts — 손대지 말 것 (categories.ts 를 고치고 다시 돌린다)
-- 이름·설명·토픽을 이어 붙인 검색용 문자열. 양끝의 공백이 문자열 처음·끝의
-- 단어 경계다. 구분자는 펴지 않는다 — 경계는 GLOB 패턴 쪽이 갖는다.
CREATE VIEW IF NOT EXISTS repo_text AS
SELECT
  s.repo_id,
  s.full_name,
  ' ' || lower(s.full_name || ' ' || coalesce(json_extract(s.data, '$.description'), '') || ' ' || coalesce((SELECT group_concat(j.value, ' ') FROM json_each(s.data, '$.topics') j), '')) || ' ' AS hay
FROM star s
WHERE s.unstarred_sync IS NULL;

-- 분류의 정의. 느리지만 authoritative 다 — repo_category 는 이걸 굳힌 것이다.
-- repo 하나가 여러 도메인에 걸린다. ord 는 CATEGORIES 순서(= 우선순위).
CREATE VIEW IF NOT EXISTS repo_match AS
SELECT repo_id, full_name, 'ai' AS category, 1 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]ai[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]llm[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]llms[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]gpt[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]gpt[^a-z0-9]4[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]chatgpt[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]openai[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]anthropic[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]claude[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]gemini[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]ollama[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]langchain[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]rag[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]embedding*'
    OR hay GLOB '*[^a-z0-9]machine[^a-z0-9]learning[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]deep[^a-z0-9]learning[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]neural*'
    OR hay GLOB '*[^a-z0-9]transformer*'
    OR hay GLOB '*[^a-z0-9]diffusion[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]stable[^a-z0-9]diffusion[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]copilot[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]mcp[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]agentic[^a-z0-9]*'
UNION ALL
SELECT repo_id, full_name, 'editor' AS category, 2 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]editor[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]editors[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]wysiwyg[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]rich[^a-z0-9]text[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]contenteditable[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]prosemirror[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]codemirror[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]monaco[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]slate[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]lexical[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]tiptap[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]quill[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]markdown[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]mdx[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]remark[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]rehype[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]syntax[^a-z0-9]highlight*'
    OR hay GLOB '*[^a-z0-9]highlight[^a-z0-9]js[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]prism[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]shiki[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]vim[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]neovim[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]emacs[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]vscode[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]textarea[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]diff[^a-z0-9]*'
UNION ALL
SELECT repo_id, full_name, 'viz' AS category, 3 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]chart[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]charts[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]charting[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]graph[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]graphs[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]plot[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]plots[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]plotting[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]visualization[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]visualisation[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]dataviz[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]data[^a-z0-9]viz[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]d3[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]echarts[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]chartjs[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]visx[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]canvas[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]webgl[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]webgpu[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]three[^a-z0-9]js[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]shader*'
    OR hay GLOB '*[^a-z0-9]svg[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]geospatial[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]cartograph*'
    OR hay GLOB '*[^a-z0-9]diagram*'
    OR hay GLOB '*[^a-z0-9]animation[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]animations[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]motion[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]gsap[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]easing[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]lottie[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]sprite*'
UNION ALL
SELECT repo_id, full_name, 'test' AS category, 4 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]test*'
    OR hay GLOB '*[^a-z0-9]jest[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]vitest[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]mocha[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]jasmine[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]karma[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]playwright[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]puppeteer[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]cypress[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]selenium[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]webdriver[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]e2e[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]mock*'
    OR hay GLOB '*[^a-z0-9]stub*'
    OR hay GLOB '*[^a-z0-9]fixture*'
    OR hay GLOB '*[^a-z0-9]assertion*'
    OR hay GLOB '*[^a-z0-9]coverage[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]snapshot[^a-z0-9]testing[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]benchmark*'
    OR hay GLOB '*[^a-z0-9]fuzz*'
UNION ALL
SELECT repo_id, full_name, 'cli' AS category, 5 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]cli[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]command[^a-z0-9]line[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]commandline[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]terminal[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]tui[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]shell[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]bash[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]zsh[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]fish[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]dotfiles[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]prompt[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]ansi[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]tty[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]curses[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]scaffold*'
    OR hay GLOB '*[^a-z0-9]generator[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]boilerplate[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]starter[^a-z0-9]*'
UNION ALL
SELECT repo_id, full_name, 'build' AS category, 6 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]bundler[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]bundling[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]webpack[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]rollup[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]vite[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]esbuild[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]swc[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]parcel[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]turbopack[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]babel[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]compiler[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]transpil*'
    OR hay GLOB '*[^a-z0-9]eslint[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]lint*'
    OR hay GLOB '*[^a-z0-9]prettier[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]formatter[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]monorepo[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]workspace*'
    OR hay GLOB '*[^a-z0-9]pnpm[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]yarn[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]package[^a-z0-9]manager[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]build[^a-z0-9]tool[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]codemod[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]ast[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]minif*'
    OR hay GLOB '*[^a-z0-9]tree[^a-z0-9]shaking[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]polyfill*'
UNION ALL
SELECT repo_id, full_name, 'native' AS category, 7 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]ios[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]android[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]swift[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]swiftui[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]objective[^a-z0-9]c[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]kotlin[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]flutter[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]react[^a-z0-9]native[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]expo[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]electron[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]tauri[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]macos[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]windows[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]linux[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]desktop[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]mobile[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]native[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]xcode[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]gtk[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]qt[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]wasm[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]webassembly[^a-z0-9]*'
UNION ALL
SELECT repo_id, full_name, 'server' AS category, 8 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]server[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]backend[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]api[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]rest[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]graphql[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]grpc[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]rpc[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]http[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]https[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]websocket*'
    OR hay GLOB '*[^a-z0-9]database[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]db[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]sql[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]sqlite[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]postgres*'
    OR hay GLOB '*[^a-z0-9]mysql[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]redis[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]mongodb[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]orm[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]query[^a-z0-9]builder[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]migration*'
    OR hay GLOB '*[^a-z0-9]auth[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]authentication[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]oauth[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]jwt[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]session*'
    OR hay GLOB '*[^a-z0-9]cache[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]caching[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]queue[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]proxy[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]router[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]routing[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]serverless[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]docker[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]kubernetes[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]deploy*'
    OR hay GLOB '*[^a-z0-9]nginx[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]middleware[^a-z0-9]*'
UNION ALL
SELECT repo_id, full_name, 'docs' AS category, 9 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]awesome[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]awesome[^a-z0-9]list[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]curated[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]documentation[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]docs[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]tutorial*'
    OR hay GLOB '*[^a-z0-9]guide[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]guides[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]book[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]books[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]course[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]courses[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]cheatsheet[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]cheat[^a-z0-9]sheet[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]learn[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]learning[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]roadmap[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]interview[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]interviews[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]example*'
    OR hay GLOB '*[^a-z0-9]demo[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]demos[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]blog[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]handbook[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]reference[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]spec[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]rfc[^a-z0-9]*'
UNION ALL
SELECT repo_id, full_name, 'ui' AS category, 10 AS ord
FROM repo_text WHERE hay GLOB '*[^a-z0-9]ui[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]ui[^a-z0-9]kit[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]component[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]components[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]design[^a-z0-9]system[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]react[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]reactjs[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]vue[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]vuejs[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]svelte[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]angular[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]solid[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]preact[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]headless[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]shadcn[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]radix[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]chakra[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]mui[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]material[^a-z0-9]ui[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]ant[^a-z0-9]design[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]bootstrap[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]tailwind[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]tailwindcss[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]css[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]scss[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]sass[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]css[^a-z0-9]in[^a-z0-9]js[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]styled[^a-z0-9]components[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]emotion[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]stylex[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]storybook[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]form[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]forms[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]modal[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]dialog[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]dropdown[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]tooltip[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]accessibility[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]a11y[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]aria[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]layout[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]grid[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]flexbox[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]theme[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]theming[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]dark[^a-z0-9]mode[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]icon[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]icons[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]font[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]fonts[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]typography[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]hooks[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]state[^a-z0-9]management[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]frontend[^a-z0-9]*'
    OR hay GLOB '*[^a-z0-9]web[^a-z0-9]components[^a-z0-9]*';

-- 굳힌 분류. make-views.ts 가 repo_match 로 채운다.
CREATE TABLE IF NOT EXISTS repo_category (
  repo_id   INTEGER NOT NULL,
  full_name TEXT    NOT NULL,
  category  TEXT    NOT NULL,
  ord       INTEGER NOT NULL,
  PRIMARY KEY (repo_id, category)
) WITHOUT ROWID;

CREATE INDEX IF NOT EXISTS repo_category_category ON repo_category(category);

-- 대표 도메인. SQLite 는 min() 과 함께 쓴 bare column 을 그 최소 행에서 가져온다.
CREATE VIEW IF NOT EXISTS repo_primary_category AS
SELECT repo_id, full_name, category, min(ord) AS ord
FROM repo_category
GROUP BY repo_id;
-- <<< generated
