import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import { categoryViewsSql, REFILL_CATEGORIES } from './src/categories.ts'

// 분류 뷰는 categories.ts 에서 찍어낸다. 이 스크립트가 views.sql 의 생성 구간만
// 갈아끼우고, db 경로를 주면 파일 전체를 그 db 에 적용한다.
//
//   node make-views.ts                # views.sql 만 갱신
//   node make-views.ts ../stars.db    # 갱신 후 db 에 적용

const BEGIN = '-- >>> generated by make-views.ts — 손대지 말 것 (categories.ts 를 고치고 다시 돌린다)'
const END = '-- <<< generated'

const path = join(import.meta.dirname, 'sql/views.sql')
const current = readFileSync(path, 'utf8')
const block = `${BEGIN}\n${categoryViewsSql()}\n${END}`

const start = current.indexOf(BEGIN)
const stop = current.indexOf(END)
const next =
  start === -1 || stop === -1
    ? `${current.trimEnd()}\n\n${block}\n`
    : `${current.slice(0, start)}${block}${current.slice(stop + END.length)}`

writeFileSync(path, next)
console.log(`views.sql 갱신 — 분류 뷰 ${next.length}B`)

const dbPath = process.argv[2]
if (dbPath) {
  // 생성 구간은 CREATE VIEW IF NOT EXISTS 라 이미 있으면 조용히 지나간다.
  // 정의가 바뀌었을 수 있으므로 분류 뷰는 먼저 떨어뜨리고 다시 만든다.
  const db = new DatabaseSync(dbPath)
  for (const v of ['repo_primary_category', 'repo_match', 'repo_text']) {
    db.exec(`DROP VIEW IF EXISTS ${v}`)
  }
  db.exec(next)
  // 규칙이 바뀌었을 수 있으므로 굳힌 표는 매번 통째로 다시 채운다.
  db.exec(REFILL_CATEGORIES)
  const n = (db.prepare('SELECT count(*) AS n FROM repo_category').get() as { n: number }).n
  db.close()
  console.log(`${dbPath} 에 적용 — 분류 ${n}건`)
}
